controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    hw_params:
      is_sim: true
      delay: 0.009 # 仿真通信延迟，单位秒
    imu_params:
      accel:
        variance: 0.0       # 测量协方差
        bias_mean: 0.0       # 静态偏置，模拟真机安装/芯片误差
      gyro:
        variance: 0.0004
        bias_mean: 0.0
      orientation:
        variance: 0.0012
        
    DogNmpcWbcController:
      # type: dog_controllers/DogNmpcWbcController
      type: dog_controllers/DogNmpcWbcController_God
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
      
DogNmpcWbcController:
  ros__parameters:
    threshold: 0.01
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
    contacts:
      - LH_contact_sensor
      - RF_contact_sensor
      - LH_contact_sensor
      - RH_contact_sensor

joint_state_broadcaster:
  ros__parameters:
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE

effort_controller:
  ros__parameters:
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
    interface_name: effort
    
imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link